#base "../../cfg/hud_basechat.txt"
#base "../_jofrenew/resource/chatscheme_new.res"
#base "../_jofrenew/resource/chatscheme_tf2exp.res"
#base "../_jofrehud/resource/chatscheme.res"
#base "../_jofrehud/_tf2exp/chatscheme.res"